language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script: pytest --cov=smtp2go tests/
after_success:
- coveralls
notifications:
  slack:
    secure: LlCh6lZOxLcvZ/BuA+QOMuENYbJlyYpDiwxifiKERXKyneYLZwMw+iqWh687Ak1F/NIDe7vPfyTLF0PMVfQ9hIbQUmiYQbUPdjwaxHY0zsZyc6l4qUf4aecgTmZBBSbSOvCD+sH4UAkEbN79FjlcQqnhMf+uios3hcXFQOFTb1SM8QIiGEfvfLa/kA0pXuATrbDfPhAv6domyLnMro6+5pVefjin5Dh2daybzWKNn17xLj8LTfe5ADocXfpM70sxkV3EsxKTDnG1qrcatxb0sWUNNdfB2g8ZGIPYSXcqSfEOTsOCfPfRSJp95+JLYqiNEPB/l1lnwcBy2IFhnyKKK1IPB4SofXIJCqTvHJo6bDYvQYelzSGrQa9IfpsYn3JDyob/33qICDdM6lhcZpCHWWM1ifQZlT4P6YGAEgMeLonVl7KfIfS37WE923q8UVjJVbDO3wKaCMrEK/XrvCjzUYQm1ieno9lVF3AnhGdkeBq+RJO+modmst9JochUGbPX3SdetKF/ft6woXWUAfXR0Q87wbJb81ERkNLOsTdMjDEWRQ2KkC8Em+eiwFyrBB7ybWdx9JDOusmng1DJCcAvRC55l23vOeFx69tPQzgWe/LbgTlqaJWm5ecYO8WDyFv29D2bA23FKLQHU38r8fhYnkr+LKLGhjGazjrsIUJdDE0=
